Improve builder build script.

diff --git a/openwrt/scripts/docker-build-builders b/openwrt/scripts/docker-build-builders
--- a/openwrt/scripts/docker-build-builders
+++ b/openwrt/scripts/docker-build-builders
@@ -4,13 +4,15 @@ work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
 platform_dir="${work_dir}/openwrt"
 version=$(git describe --always)
 
-branches="$(cat ${platform_dir}/branches)"
+branch_config="$(cat ${platform_dir}/branches)"
 architectures="$(cat ${platform_dir}/architectures)"
+push=0
 
 while [ -n "$1" ]; do
   case "$1" in
     -b) branches="$2"; shift ;;
     -a) architectures="$2"; shift ;;
+    -p) push=1 ;;
     -*)
       echo "Invalid option: $1"
       exit 1
@@ -22,15 +24,22 @@ while [ -n "$1" ]; do
   shift;
 done
 
+if [ -z "${branches}" ]; then
+  echo "No branch specified. Use -b <branch> to specify a branch."
+  exit 1
+fi
+
 echo "Creating runtime Docker containers..."
 echo -n "Branches: "
 echo $branches
 echo -n "Architectures: "
 echo $architectures
 
-for branch in ${branches}; do
+for branch in ${branch_config}; do
   short_branch=$(echo $branch | cut -d ':' -f 4)
   branch=$(echo $branch | cut -d ':' -f 1)
+
+  (echo $branches | grep $branch >/dev/null) || continue;
 
   for architecture in ${architectures}; do
     image_name="wlanslovenija/openwrt-builder:v${version}_${short_branch}_${architecture}"
@@ -42,12 +51,14 @@ for branch in ${branches}; do
     if [ "$?" == "0" ]; then
       echo "ok"
 
-      echo -n "  - Pushing image ${image_name}... "
-      docker push ${image_name} >/dev/null 2>/dev/null
-      if [ "$?" == "0" ]; then
-        echo "ok"
-      else
-        echo "failed!"
+      if [ "${push}" == "1" ]; then
+        echo -n "  - Pushing image ${image_name}... "
+        docker push ${image_name} >/dev/null 2>/dev/null
+        if [ "$?" == "0" ]; then
+          echo "ok"
+        else
+          echo "failed!"
+        fi
       fi
     else
       echo "(skipped)"
