buildsystem: Fully rework
Completely rework the current build system.
Switch from building from source to using the upstream provided imagebuilder.

Use upstream SDK to build not yet upstreamed packages like tunneldigger.

This change is drop in compatible with Nodewatcher as the same image type is generated at the end.

Both base and runtime has been updated to use Ubuntu 18.04.

There are still improvements to be made in the following time.

Signed-off-by: Robert Marko <robimarko@gmail.com>

diff --git a/openwrt/scripts/docker-build b/openwrt/scripts/docker-build
--- a/openwrt/scripts/docker-build
+++ b/openwrt/scripts/docker-build
@@ -1,4 +1,4 @@
-#!/bin/bash -x
+#!/bin/bash
 
 openwrt_version="$1"
 openwrt_target="$2"
@@ -6,7 +6,6 @@ openwrt_subtarget="$3"
 work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
 platform_dir="${work_dir}/openwrt"
 build_dir="${work_dir}/build"
-download_dir="${build_dir}/openwrt"
 
 if [[ -z "${openwrt_version}" || -z "${openwrt_target}" || -z "${openwrt_subtarget}" ]]; then
   echo "ERROR: Usage: $0 <version> <target> <subtarget>"
@@ -29,10 +28,8 @@ else
 	target_url="${base_url}/snapshots/targets/${openwrt_target}/${openwrt_subtarget}"
 fi
 
-mkdir -p ${download_dir}
-
 # Get imagebuilder & SDK archive section
-cd ${download_dir}
+cd ${build_dir}
 
 # Get imagebuilder filename
 imagebuilder_filename=$( curl -s -L "${target_url}" | grep openwrt-imagebuilder | grep -o '<a href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^<a href=["'"'"']//' -e 's/["'"'"']$//' )
@@ -49,27 +46,72 @@ echo "Downloading SDK for ${openwrt_target}-${openwrt_subtarget}"
 curl -O "{$target_url}/{$SDK_filename}"
 
 # Make imagebuilder directory
-mkdir -p imagebuilder-${openwrt_target}-${openwrt_subtarget}
+mkdir -p imagebuilder
 
 # Extract the imagebuilder
 echo "Extracting imagebuilder for ${openwrt_target}-${openwrt_subtarget}"
-tar xf $imagebuilder_filename --strip-components=1 -C imagebuilder-${openwrt_target}-${openwrt_subtarget}
+tar xf $imagebuilder_filename --strip-components=1 -C imagebuilder
 
 # Make SDK directory
-mkdir -p SDK-${openwrt_target}-${openwrt_subtarget}
+mkdir -p SDK
 
 # Extract the SDK
 echo "Extracting SDK for ${openwrt_target}-${openwrt_subtarget}"
-tar xf $SDK_filename --strip-components=1 -C SDK-${openwrt_target}-${openwrt_subtarget}
+tar xf $SDK_filename --strip-components=1 -C SDK
 
 # Delete imagebuilder and SDK archives
 rm $imagebuilder_filename
 rm $SDK_filename
 
 # Wlan SI custom package building section
-cd SDK-${openwrt_target}-${openwrt_subtarget}
+cd SDK
+
+# Fix LC_TIME error
+export LC_ALL=C
 
 # Add Wlan SI OPKG feed
-echo "src-git routing_wlansi https://github.com/wlanslovenija/firmware-packages-opkg.git" >> feeds.conf.default
+echo "src-git wlansi https://github.com/robimarko/firmware-packages-opkg.git" >> feeds.conf.default
 
 # Disable default options
+echo "# CONFIG_ALL_NONSHARED is not set" >> .config
+echo "# CONFIG_ALL_KMODS is not set" >> .config
+echo "# CONFIG_ALL is not set" >> .config
+echo "# CONFIG_SIGNED_PACKAGES is not set" >> .config
+
+# Update feeds
+echo "Updating feeds..."
+./scripts/feeds update -a || {
+  echo "ERROR: Failed to update feeds."
+  exit 1
+}
+
+# Install packages
+for package in $(cat ${platform_dir}/packages); do
+  package="$(echo ${package} | cut -d '@' -f 1)"
+
+  ./scripts/feeds install -p wlansi ${package}
+done
+
+# Configure packages to be built
+for package in $(cat ${platform_dir}/packages); do
+  package="$(echo ${package} | cut -d '@' -f 1)"
+
+  echo "CONFIG_PACKAGE_${package}=m" >> .config
+done
+
+# Generate config
+make defconfig
+
+# Download package sources
+make download V=s
+
+# Starting building
+make V=s
+
+# Copy built packages to the imagebuilder
+cd ${build_dir}
+find SDK/bin/targets/${openwrt_target}/${openwrt_subtarget}/packages/ -type f -name 'kmod-*' -delete
+cp -r SDK/bin/targets/${openwrt_target}/${openwrt_subtarget}/packages/. imagebuilder/packages/
+
+# Delete the SDK
+rm -rf SDK
